### PR TITLE
Ability to write wrapper VIs for assert VIs without redefining tests

### PR DESCRIPTION
**Pull request by SRM256**
This change exposes an optional (not recommended or required) input on all of the Assert ____ VIs. By making that number larger, one can create subVIs that operate like asserts for more complex compound operations, thus avoiding the noise in the test window of defining new tests at every subVI call in the hierarchy.

### CODE REVIEW

**Comment by francois-normandin** [comment]
@SRM256 
I'm intrigued, but I have to admit that I don't immediately see the use case. When I pulled your branch and inspected the changes, I thought I understood... but then I ran a couple Test Suites and looked at both the GUI and the Test Result class, with and without the proposed changes, and I could not find a difference in output. (Knowing the author's wit, ) I must be missing something. How does the registration of the call chain affect the organization of your test suite?

Would you have a demo shows the difference, with and without the call chain offset?

**Comment by SRM256** [comment]
I added a test to the test suite that shows it. You have an existing demo
of an assert that does not go off in a subVI. Mine, which wires a "3" to
the parameter, shows a subVI in which the assert does happen.

**Comment by francois-normandin** [comment]
Yes, this is what I ran. I also added it to a test suite and inspected the TestResult output where I expected a change in the Call Chain or the organization of the results.  I have not seen any changes to the result whether I keep the constant = 3, or I remove it to simulate current functionality.

**Comment by francois-normandin** [comment]
Wait... your test uses the "Asset Only" terminal = True.
Would it change the result if it is left to False?

**Comment by SRM256** [comment]
Without a "Define Test" call in the same VI as the assert, the assert does
not work (see your existing test for subVIs).
By increasing the ignore depth, the call chain computed is now at the same
level as the Define Test, so the assert does work.

**Comment by SRM256** [comment]
I'm signing off for tonight... I can try writing it up better tomorrow.

**Comment by francois-normandin** [comment]
Ohh, that's the thing I was missing.
I like it. 👍

**Comment by francois-normandin** [comment]
@SRM256 I've had a chance to review the changes and I really like the feature. I has been suggested a few times in the threads without actual proposal on how to do it and you've found a way that is simple and minimally invasive to the current code base.

I had to change your example (Test Assert in Assert Wrapper.vi) to make the example work. The reason I didn't see the effect of your change earlier is that the ignore depth had been set on the wrapped assert that was using the "Assert Only" flag = TRUE, which meant it was always ignored. Your example works as you described when I move the actual assert inside the wrapper: it does not show up in Caraya Test Manager when run as a standalone VI, but it links it to the Test ID as defined by the caller when the ignore depth = 3.

image

As I was doing the review, four things came to me.

1- The terminal "call chain ignore depth" with a default value of "2" is a bit counter-intuitive for a developer. For a regular user of Caraya that is not familiar with the inner workings of the framework, the first question I'd have is "Why is the default value 2?" The answer requires knowledge of the call chain's relation to how the Unique Test ID is formed in Caraya. This is something that is private to the inner workings of the framework, and thus it could change in the future. Exposing this terminal feels like a leaky abstraction to me. The fix for this is, I think, simply to set the default value to "0" and do the math under the hood. It transforms the question "Why is the default value 2?" into a discussion about how deep is your assertion compared to the Test Definition. Simple change that moves the narrative more in line whit the user expectation from an API perspective.

2- Then I thought, well this is all fine from an API perspective, but what happens if I change my VI call chain, such as selecting the block diagram of a large test and making it a subVI. If I forget to change the call chain depth, my test won't register anymore, and if I want this VI to be reusable, do I always know the depth where it will be? If I want to reuse the sub-test, will I need to also carry around the call chain depth terminal on its conpane? Will I remember what this is for in 6 months? Will I remember to check all the spots where I used it in case I mess something up in the refactor?

### "Real-life" parabola

I have a wonderful test suite that is called "Test my Universe" which is composed of a staggering 5237 tests. They all pass, great piece of art. It happens that the 42nd test in this suite is labeled "End of the Universe" and uses the call chain depth = 3 .

The CI server runs a simulation of my universe and reports that all tests have passed. I have a stable universe.

Five months down the road, I want to modify the suite to test a new paradigm: "[CCC](https://en.wikipedia.org/wiki/Conformal_cyclic_cosmology)". I notice that it is similar to another test called "End of the Universe", where instead of the limit when time goes to infinity, I can reuse some of the code and replace the limit where time goes to infinity with a transform that makes infinity be equivalent to t = 0. 

How to proceed. First, let's copy the test and label it "Test CCC".
Because the conformal geometry invariance algorithm is still being developed, I'll first make sure to have the test fail... I replace "Infinity" with "0" and run just the new test without any actual transformation. Lo and behold, it fails. That's great, now I can add the test to my full suite and be certain that the test won't pass until we have a working CCC-transform algorithm.
But I don't like the test abstraction, so I'll wrap this new test into a CCC Test class and create a "Test CCC.vi" method which calls the wrapper VI. But wait, now the test suite passes... why? Oh, I forgot to change the call chain depth. I change it from 3 to 4, and run it again. Yes, the suite fails now... My job is done... some other smart folks will now work on the CCC algorithm and run test suite when they think it will pass. As a last sanity check, I disable my test and make sure the test suite passes. It does, but I fail to notice that it now runs only 5236 tests...

I think I can stop the story here... we all know what I've done wrong: I unknowingly modified the 42nd test in a way that the framework is going to ignore it. The test suite fails now, and will work when the CCC algorithm passes the test, but I might have done something to the fundamental laws of the universe that would make the answer to my forgotten test be somewhat different than I expected. 

I'll discuss how I think we can fix this after the next point... which makes a change inevitable because I found that it does break a current feature of the framework...

3- Show stopper: I checked that I could still navigate to the assert by double-clicking on the assert result in the UI: it does not work anymore. The reason is that we use the call chain to match the "Assertion Unique ID" with the actual assert VI that was called. Now, the VI Call Chain is different and the only way to fix this would be to store the full call chain along with the ignore depth and make it part of the result report. It becomes a bit convoluted, although certainly doable. 

4- Finally, by choosing to not define a test in each VI where we make assertions, we have to expect that those asserts MIGHT be skipped when using the "Run Test" methods (that is, running the tests from QD plugin, all tests in folder, all tests in project reference, all tests in object, etc.) This is OK. We are not using a "Run Asserts" method, but a "Run Tests" method... so I don't think it breaks the definition... but it is something to keep in mind. The result might not be what the user expects, although it is a direct consequence of knowingly use the call chain depth feature.

### Potential Solution

The problem statement: 
- We want to evaluate assertions that are called by a test even though the test is declared in a caller VI.
- We still want to use the assert method as a simple assertion which should not be associated with a registered test unless the developer specifically flags it (currently with call chain depth != 2 and matching a Define Test at the exact depth specified)
- We want to carry the assert call chain so it can both be associated with the "Unique Test ID" and its own "Unique Assertion ID".

Assumption I make: 
- I is unlikely that anyone would write an assertion inside a test hierarchy and not want to run it depending on how deep it is in the hierarchy. In other words, does it matter that it is located exactly at depth = 3, 4 or 5? 

Proposed solution: 
- Replace the "call chain ignore depth" input terminal with a boolean flag called "register with calller test" or something like that.
- The boolean flag would be false by default
- The presence of the flag would instructs the "Test Assert Factory.lvclass:Read Assert.vi" method to iterate on the call chain to match the first registered test in the call chain.
- Failing to find one, it does not change the current behavior
- Succeeding in finding one, only the Unique Test ID would be changed in the report, correctly associating the assert with its test.

image

image


**So I'm going ahead and pulling your changes to "develop" branch and I'll be adding a few changes for further discussion in the main threads.**

**Comment by SRM256** [comment]
You gave me an idea: Instead of a bool or integer, how about a string.
Defaults to empty string. You pass the name of the first VI you want to be
ignored in the call chain. Lower-level VIs would pass their own names
unless the string is already not empty. When the call chain is looked up,
just drop terms until the named term is found. That makes this
resilient even against change to Caraya's deep layers, and it avoids any
sort of registration table.

**Comment by SRM256** [comment]
Alternatively, keep the registration table and get rid of the input
terminal entirely. Simply have any VI that wants to act like a top-level
assert VI add its name to a set of VI names (it can do this once on first
call). Then when the call chain is looked up, test each segment for
presence in the set. Take the highest level name that is in the set and
drop everything from that point down. This way there's no new terminal to
appear in the public API at all, and we are still safe against refactoring.
It also means that the one assert VI that doesn't have space left on its
conpane can be wrapped.

**Comment by francois-normandin** [comment]
Hmmm. looks like this last alternative could be set at the "Define Test" method, where a flag or "array of tags" would instruct the framework to pull in any loose asserts under its hierarchy. The flag option would be similar to replacing the boolean terminal, whereas the array of tags would allow the developer to drop a tagging VI on the same block diagram as the loose assertion to link the names.

Does that sound like it would be something less complex for developers to use?

I think I'll move this discussion to the main issue board for a wider discussion. I fear that the "pull request" thread does not attract the same level of attention.

**Comment by SRM256** [comment]
Making it part of "Define Test" doesn't sound like a good option at all...
there aren't any calls to Define Test in the standard assert VIs, and it
wouldn't make any sense to me to add it to the higher level assert VIs. If
you like the second solution that I sent, then just add a new VI for
"Register As Assert VI.vi" -- doesn't even need any parameters if you want
to write it as getting the Call Chain inside itself.

**Comment by francois-normandin** [comment]
But you always have to have at least one "Register Test" method at the top-level of your tests... otherwise the assertion is ignored by the framework and acts as a simple frameworkless assert VI.

Yes, adding a Register as Assert VI is what I was referring to. A node to be used to set the tag.

**Comment by francois-normandin** [comment]
The VI below will not register itself with the framework: 
image

It has to be called by at least one top-level test VI like below: 
image

Running the bottom VI will yield no result in Caraya.
Running the top one is what you're after, right? The ability to run multiple assertions in subVIs without having a broken down hierarchy is the ultimate goal...

A vs B:
image

**Comment by francois-normandin** [comment]
I'll throw down a quick proposal of your tag idea. I agree with you that there is value of not having any terminal input and the Register as Assert VI would definitely work.

**Comment by francois-normandin** [comment]
Re-reading your comments, I find myself thrown a bit off-course by this part:

> Simply have any VI that wants to act like a top-level assert VI add its name to a set of VI names (it can do this once on first
call). Then when the call chain is looked up, test each segment for presence in the set. 

I am not sure what your use case is to omit the "Define Test" method... as it is a departure from how the framework is set to work and adding a "Register as Assert VI" is kind of what you're asking for.

I think I do not yet grasp the full scope of what you want to achieve by avoiding this node. Is there something that is impossible to do at the moment (assuming assertions can be organized hierarchically as shown in the above screenshots without repeating the Define Test method everywhere)?

**Comment by tmaila** [comment]
I made a mistake originally by creating one framework that combined asserts for unit testing and asserts for, well, asserting. I think that is confusing and most people don't use the asserts in Caraya for asserting but only for unit testing. I believe the work-around introduced in this PR is not the right solution. I suggest, that in Caraya 2.0 we separate the two concepts as they should originally have been separated. We should have a separate LabVIEW assertion library that has nothing to do with unit testing and Caraya assertion library that always triggers a unit test event. That design would render this PR unnecessary. In this 2.0 version Caraya asserts should all convert into unit testing asserts. Each VI having asserts would automatically become a test even when define Test is not present. In the data visualization layer (UI / reporting plugins) we could define how these tests without Define test are visualized. Are they grouped to the parent or not. But that is purely a visualization and data representation question. Anyone using asserts for plane old asserts we should provide a code migration tool replacing the Caraya asserts with these new LabVIEW asserts having nothing to do with unit testing.

**Comment by francois-normandin** [comment]
Thanks for chiming in @tmaila .
I agree that the assertions should be separated, but the current PR (the way I understand it) seems targeted at simplifying the test report hierarchy at its source and allow for reuse components to be created for unit testing, without having to tie these reuse blocks to a specific test report hierarchy. The ability to call an assertion as part of a reuse library certainly has value and it's been reported many times that the organization by call chain is not something that pleases everyone.
I see this PR as a way to address this concern, while not changing the Caraya 1.0 behavior.

I don't know if this is Stephen's take on this PR. Maybe you can confirm or deny my statements, @SRM256 ?

While you talk about Caraya 2.0, I would certainly like to explore it with the interfaces as part of the discussion... By the time we entertain a serious Caraya 2.0 contender, a lot of people will have moved away from LV2013 anyhow. That's a bit of wishful thinking on my part, I admit 😃

**Comment by SRM256** [comment]
I will tackle a revised PR and demo... should be Monday, but during
quarantine, sometimes I get bored and break my rules against doing my
assigned work on the weekends (coding for fun is a whole different thing).
So you might get something this evening.

Short story: I want to be able to create new Assert ___ VIs that are
wrappers around the existing Assert ____ VIs. These are not tests specific
to my unit tests. These are as if they were first class citizens of the
Caraya API for any test author to use. For example, there's an existing
"Assert Almost Equal_Float.vi" that takes a parameter... I want to create,
for example, "Assert Almost Equal Standard Distance_Float.vi" that
just passes a particular constant that we use frequently in our tests as
the parameter. I do not want that subVI to define a new test... its caller
will define the test and call that subVI. There are a few other common
wrapper VIs that I want to write. Currently, I cannot write them because of
the call chain depth problem.

**Comment by tmaila** [comment]
@francois-normandin I am not sure I see how this PR changes the fact that the tests are still executed in call chain and as such reported as part of call chain. If I understand correctly, this PR changes two things. First unit test asserts and non-unit tests asserts can be combined into a single VI. The right solution to this problem is separate the unit test asserts and non unit test asserts into two libraries IMHO. Second feature introduced by this PR is that the reporting is changed so that a parent test is used for reporting purposes. For this second problem I see two solutions that I think are better than the proposed solution. A) Add an option to the UI / reporting to group tests defined in subVIs without Define Test call with their parent (or make this the default behavior and add an option to do the opposite). B) Add an input to that Define Test node that requests overriding the default behavior of reporting / UI to report current VIs test results together with VI's parent. The challenge in general is that if the same subVIs is called multiple times, how do you report the multiple outcomes. That challenge applies to this PR and to my proposal both.

**Comment by francois-normandin** [comment]
This PR changes the association of the "Unique Assert ID" to the "Unique Test ID".
Without this change, an assert does not register with a test if the call chain does not match "depth = 2". With this PR, we can set specify that an assertion is part of a prior defined test. 

If it is a simple assert, you set the "Assert Only" flag to True and it's a moot point.
If the assert should be registered without "Define Test", then it just iterates the call chain until it finds the first "Define Test". If none found, then it acts as a simple assert.

I don't think it fundamentally changes much, and if it's just a matter of VI hierarchy, that could be handled in the Test Result class on the other end as well. I think what is at stake here is just to find a way that allows infinite control on the reuse test code and decide at runtime if and when it is a part of a certain test. 

I might have an entirely different solution based on what Stephen described in his latest post... I think it clarified the intent a lot for me, and that spring some additional thoughts for me as well... I'll take a walk and think a bit more about it with fresh air. Sometimes it helps :-)

**Comment by francois-normandin** [comment]
ok, my idea would require that the Assert Factory be exposed for extension, not just the Assert class. It is currently private for good reasons, so I think it requires too much of a change to explore.

**Comment by francois-normandin** [comment]
> I want to create, for example, "Assert Almost Equal Standard Distance_Float.vi" that just passes a particular constant that we use frequently in our tests as the parameter. I do not want that subVI to define a new test... its caller will define the test and call that subVI. There are a few other common wrapper VIs that I want to write. Currently, I cannot write them because of the call chain depth problem.

I believe the latest develop branch (with the flag) would work in this case.
I've added an example in the project. Can you tell me if this covers your use case or if it is still an incomplete coverage if the desired feature?
image

Note that I put the reuse component as a member of a class that inherits from Assert class, but it is not necessary since the methods it uses are public anyway...

**Comment by jimkring** [comment]
Hi all! I'm enjoying this discussion :)

I've enabled the new "Discussion" feature/area of the Caraya project. It's
easy for a project admin to move/migrate an existing Issue to the
Discussion:
https://github.com/JKISoftware/Caraya/discussions

-Jim

**Comment by SRM256** [comment]
I just put a new pull request up with a complete variation on my previous
bowl.

**Comment by jimkring** [comment]
I like it when you "bowl with us :)

(not sure if others know what you mean, but I do)
-- 
Jim Sent from my mobile.

**Pull request merged**
