### PR TITLE
Added support for running Caraya from exe

### PR DESCRIPTION
**Pull request by omarmussa**
Updated build process to write Library info to a constant so that library info source files do not need to exist when running from EXE or built package.  Note that to run Caraya in a built executable you must explicitly add Caraya.lvlib to the "Always Included" list in the build.

### CODE REVIEW

**Comment by omarmussa** [comment]
Note - I tested the change in a local build of the package but did not include the changed .vipb file so that release notes and build process can be managed by JKI.

**Comment by omarmussa** [comment]
@jimkring I can help with updating the Wiki page.  Thanks for pasting in the release note as the starting point.

**Comment by neilpate** [comment]
I have created a class that implements some SQL queries, and have created Caraya tests for the public API. Additionally I have created a "Test All" which is a sequence of all of these test VIs. This all works fine from within LabVIEW.

Now I am interested in building an exe which simply calls my "Test All" on a button press. I included the Caraya.lvlib and my build seems to work but nothing much happens when I click my "Test All" button. Do I need this newer distribution of Caraya to get this to work inside an exe? Is anything else required (like not removing FPs in the Caraya summary VI?)

**Comment by jimkring** [comment]
Hi @neilpate. Would you mind posting your question into the Caraya Community Forum? https://forums.jki.net/forum/65-caraya-unit-tester/ It will keep our issue/feature tracker clean and facilitate more rich conversations about this topic. Thanks!

**Comment by omarmussa** [comment]
@neilpate I just reviewed my build and notice that I had left 'Enable debugging' checked in the build spec for the exe - will add it to the Wiki until I have time to figure out which parts are getting stripped at build time.  It may require more development to fix this issue.

**Comment by jimkring** [comment]
My guess is that front panel needs to be preserved during the build.
-- 
Jim Sent from my mobile.

**Comment by neilpate** [comment]
Will do @jimkring.

**Pull request merged**
