### PR TITLE
Fix for #124 -- Remove duplicate asserts from loops in Test Results

### LINKED ISSUE #124: Caraya Report contains duplicates of every assert regardless of hierarchy
When I call test VIs in a loop, Caraya seems to get confused about which parent a given assert refers to. In the image, the tree is correct. The JUnit XML contains a ton of duplicate entries

image

image

### PR DESCRIPTION
**Pull request by tannerblair**
Why should you merge this:
Fixes #124 by looking up test results by ID rather than by callchain.

Testing:
Manually verified, and added a basic test to ensure that the quantity of the generated results is valid. More thorough testing would be good for report generation in general, but this should at least affirmatively confirm that the bug in #124 isn't occurring.

### CODE REVIEW

**Comment by francois-normandin** [comment]
Hi @tannerblair 
Thanks for the contribution. I have not had time to review it yet, but I don't think we can accept this pull request because the NI XML parser dependency is not cross platform and won't run in RT.

**Comment by tannerblair** [comment]
@francois-normandin, the xml parser is only used in a unit test, not in the implementation.

**Comment by francois-normandin** [comment]
@tannerblair OK, my mistake. When I saw the dependency on NI.XML, I admit I didn't look at the code at all. I could have committed a change to remove the dependency or making sure it was excluded from the built package.

Although, as mentioned in #124 discussion thread, there was already a node for the sort by TestID, so I used it instead.
Thanks for this contribution. Very much appreciated. You did all the heavy lifting 👍

**Comment by jimkring** [comment]
Kudos @tannerblair!

**Pull request closed without merging**
