### PR TITLE
Remove OpenG dependency

### PR DESCRIPTION
**Pull request by volks73**
First, I would like to mention that I have been using Caraya in a variety of projects and I love it. It just fits my needs perfectly for unit and integration testing within LabVIEW. Thank you so much for creating this useful package. However, I have encountered one problem associated with the OpenG dependency when using Caraya that I thought I might be able to fix.

The `Register Check Running.vi` uses an OpenG VI to filter an array based on if the array was empty or not. The usage of this OpenG VI required the installation of the OpenG Array library/package, which is
not a big deal, except for two reasons: (1), the OpenG VI dependency is only used within the `Register Check Running.vi` within the Caraya project. It feels a little excessive to add a dependency for single usage, especially given the relative simplicity of the functionality that is implemented and (2), more importantly, the OpenG Array library is installed into `user.lib` instead of `vi.lib` for legacy reasons and this causes problems when using Caraya in a project and attempting to save for previous version. 

When using the Save for Previous Version... action from the __File>>Save for Previous Version...__ of the _Project Explorer_, the `vi.lib` is excluded, but the `user.lib` is not. The OpenG dependency then gets saved along with the rest of the project with the full folder hierarchy from the C drive on a Windows machine. For example, LabVIEW and the OpenG dependency are installed in the default locations on a Windows machine, i.e. `C:\Program Files (x86)\National Instruments\LabVIEW 2017` and `C:\Program Files (x86)\National Instruments\LabVIEW 2017\user.lib\_OpenG.lib\array\array.lib`, and I have a project saved at `C:\Users\example_user\Documents\Projects\Example Using Caraya`. When I save for previous version the Example Using Caraya project to an output folder at `C:\Users\example_user\Documents\Projects\output`, I will get the following folder structure in `output`, where `+` indicates a folder and `...` additional files and folders omitted for clarity:

```text
output
+ C
|  +  Program Files (x86)
|  |  +  National Instruments
|  |  |  +  LabVIEW 2017
|  |  |  |  +  user.lib
|  |  |  |  |  +  _OpenG.lib
|  |  |  |  |  |  +  array
|  |  |  |  |  |  |  +  array.lib
|  |  |  |  |  |  |  |  ...
|  +  Users
|  |  +  example_user
|  |  |  +  Documents
|  |  |  |  +  Projects
|  |  |  |  |  +  Example Using Caraya
|  |  |  |  |  |  ...
```

This is quite cumbersome and excessive to deal with when attempting to create a package for distribution, especially when only a single VI from the dependency is only used in one location within the Caraya project.

Ideally, the solution would be to have the `user.lib` folder ignored from the save for previous version action. Ignoring other folders, such as `instr.lib` or `user.lib`, appears to be under evaluation by NI
(https://forums.ni.com/t5/LabVIEW/Excluding-instr-lib-folder-from-Project-Save-For-Previous/td-p/3760288), but no timeline is given. Another solution is to have the OpenG dependency installed in `vi.lib` as opposed to `user.lib`, but this is most likely impossible because of other projects, add-ons, and packages depending on OpenG being installed in `user.lib`.

Thus, I submit this pull request which removes the OpenG dependency and avoids the problem associated with the save for previous version action. I have eliminated the need for the OpenG array dependency by simply replacing its usage with a custom implementation. Now, the `user.lib` does not get included in the save for previous version action and the number of dependencies is reduced.

### CODE REVIEW

**Comment by volks73** [comment]
>I would advise removing the lvproj file from this commit as the dependencies (under vi.lib or user.lib) will be removed from the XML file the next time the whole project is opened in IDE. Merging the project file at this time would risk conflicting with other pull requests which add or remove specific files or change their scope.

I believe I have done this using the [new Github feature](https://blog.github.com/changelog/2018-07-31-removing-files-from-a-pull-request/), but please confirm this does as requested.

**Comment by francois-normandin** [comment]
From looking at the Pull Request, I think it deleted the lvproj file instead of discarding changes, but I could be wrong.
(I cannot check the actual result as you have not pushed your branch to origin.)

**Comment by volks73** [comment]
Okay, so I guess that feature did not do what I thought. Anyways, I have pushed to origin and there now only appears one file that has changed. Sorry about that.

**Comment by francois-normandin** [comment]
Sounds good now ;-)

**Comment by jimkring** [comment]
I apologize for coming in so late into this discussion. @francois-normandin @volks73 would it work to simply change the package build specification so that this becomes an internal dependency (i.e. the OpenG VIs get built into the Caraya distribution package and the end user has no idea about it)?

**Comment by francois-normandin** [comment]
Caraya is advertised as a lightweight assertion unit test framework. I am rather supportive of the idea of removing unnecessary dependencies as much as possible. In this case, there is a single node that uses a single VI in the OpenG dependency, so I support the idea of removing it altogether.

In more general terms (about including dependencies or not in the package), I also favor a minimal package size when the dependency is freely available on the  package network (such as OpenG, JKI SM, etc.). For those that require a simpler installation process because their targets do not have internet access, could it be that there is a VIPC file provided as an optional (manual) download from the release page of Caraya? This would minimize the package size, which is makes for a faster installation process when someone already has OpenG installed...

**Comment by jimkring** [comment]
@volks73 @francois-normandin I just built a package that has internalized the OpenG VIs. You can test out how this works for you.

1. Download this file: [jki_lib_caraya_no_openg-0.5.1.33.vip.zip](https://github.com/JKISoftware/Caraya/files/2475093/jki_lib_caraya_no_openg-0.5.1.33.vip.zip)

2. Remove the .zip extension so it has only the .vip extension and then VIPM will be able to install it.

Note: This is a different package name than the official Caraya package and declares a conflict on the official Caraya package so they can't both be installed concurrently.

Also: You'll find that these OpenG VIs get installed here: vi.lib\addons\_JKI Toolkits\_Caraya_internal_deps\

**Comment by volks73** [comment]
>...You'll find that these OpenG VIs get installed here: vi.lib\addons_JKI Toolkits_Caraya_internal_deps\

Cool. If the VIs are installed outside of `instr.lib`, then it avoids the problem I was having with the Save for Previous Version action. I am good with this as a possible solution as well. Thanks.

**Comment by francois-normandin** [comment]
This merge request will be rejected and closed as there is a workaround to move <user.lib> files into internal dependencies, which stores them under the Caraya folder in <vi.lib>.
The next release (0.6.0) will use internal dependencies for all OpenG packages.
Thanks @volks73 for the suggestion.

**Pull request closed without merging**
