### PR TITLE
Updated functionallity, 2 bugs fixes

### PR DESCRIPTION
**Pull request by kosist**
Added functionallity:
- added run-time short cut menu for expand/collapse of subresults (just parent node, not all sub-nodes).

Fixed bugs:
double-click while test vi is closed
double-click on empty space_2
- when all results are collapsed, and user double-clicks on empty space of Tests indicator, error occurs. Fixed in the way, that when tag, on which double-click was done, is empty -> do no action.
double-click on empty space_1
- when test VI, which ran tests is closed, and user double-clicks on test result in the results list, error occurs (b/c VI is not in the memory anymore). Fixed in a way, that by Application Dir, search for VI by name, and if there is just 1 VI with this name, then open its BD by path, not by name.

### CODE REVIEW

**Comment by kosist** [comment]
Do I need to keep hope, that it'll be reviewed? =))) Or I did something wrong with this pull request? Please... =))

**Comment by jimkring** [comment]
Hi @kosist and thank you for your submission. Please review and sign the Contributor License Agreement, so that we can incorporate your improvements into the codebase.

**Comment by kosist** [comment]
Thanks a lot!

**Comment by jimkring** [comment]
@kosist did you make these changes?

image

It's saying that they were made by a use named "Ivan"

**Comment by kosist** [comment]
Yes, just I don't know why it is shown like that; I've always had this nickname (kosist) here... You could see it also from my fork - it has branch "test-result-UI-upd", which was pushed here as pull request...

**Comment by jimkring** [comment]
Hi @kosist. Ok, great. Thanks for answering that. Yes, it’s odd. Not a
problem.
-- 
Jim Sent from my mobile.

**Comment by jimkring** [comment]
@kosist I think we will fix the two bugs and keep the right-click menu feature for future consideration, because we're still not sure how we will use the right-click menu of the tree. See:

https://github.com/JKISoftware/Caraya/issues/27
https://github.com/JKISoftware/Caraya/issues/28

**Comment by francois-normandin** [comment]
I am closing the pull request as this will be partially implemented in release 0.6.0.

**Pull request closed without merging**
